from src.common import SAVED_MODELS_BASE_PATH

SAVED_MODELS_FASHION_MNIST_PATH = SAVED_MODELS_BASE_PATH.joinpath('fashion_mnist')
SAVED_CLASSIFIER_PATH = SAVED_MODELS_FASHION_MNIST_PATH.joinpath('classifier')
SAVED_REFAE_PATH = SAVED_MODELS_FASHION_MNIST_PATH.joinpath('refae')
SAVED_CLADEC_PATH = SAVED_MODELS_FASHION_MNIST_PATH.joinpath('cladec')
